# Generated by Django 4.2.5 on 2024-02-03 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='porcentagem_lucro',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.0'), max_digits=5),
        ),
    ]
