# Generated by Django 4.2.5 on 2024-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_produto_porcentagem_lucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
