# Generated by Django 4.2.5 on 2024-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
