# Generated by Django 4.2.5 on 2024-01-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_finalizada_alter_venda_data_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
