# Generated by Django 4.2.5 on 2024-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total_com_desconto',
            field=models.FloatField(default=0.0),
        ),
    ]
