# Generated by Django 4.2.5 on 2024-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_total_com_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada')], default='aberta', max_length=10),
        ),
    ]
