# Generated by Django 4.2.5 on 2024-02-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
    ]
