# Generated by Django 4.2.5 on 2024-02-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_remove_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
